server:
  port: ${SERVER_PORT:8080}
spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:h2:mem:testdb}
    driverClassName: ${DATASOURCE_DRIVER:org.h2.Driver}
    username: ${DATASOURCE_USERNAME:sa}
    password: ${DATASOURCE_PASSWORD:}
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
  jpa:
    database-platform: ${JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}

